### PR TITLE
Add author info to lrsManagementRest.js

### PR DESCRIPTION
**Pull request by toejough**
Give credit to the original author (me) :-)

### CODE REVIEW

**Comment by toejough** [comment]
I think that maintainers don't get emails for pull requests, but they do for comments on pull requests, so...here's a comment as a notification that I've created this pull request.

**Comment by mvachhar** [comment]
Do you want to own this in your area as the main repo until we figure out how to move this to the LineRate account?

**Comment by mvachhar** [comment]
The whole repo, I mean.

**Comment by toejough** [comment]
I'll take it if you want it out of your area, but I don't mind you holding on to it.

**Pull request merged**
